### ISSUE TITLE
404 (Not Found) error when using the extension

### ISSUE THREAD

**Issue by dt-fastec** [microsoft/azure-repos-pr-multi-cherry-pick#16]
Hi,

I want to use the extensions with Azure DevOps Server 2019, but when I use the button I get an 404 (Not Found) error.

```
Fetch.js:116 GET https://tfs01/tfs/DefaultCollection/_apis/git/pullRequests/8682 404 (Not Found)

Rejected XDM promise with no reject callbacks (Fetch.js:116)

{stack: "TFS.WebApi.Exception: 404: Not Found↵    at Object…ick/1.0.0.46/assetbyname/dist/src/app.js:8:66770)", name: "TFS.WebApi.Exception", status: 404, responseText: "Page not found.", message: "404: Not Found", …}
message: "404: Not Found"
name: "TFS.WebApi.Exception"
responseText: "Page not found."
stack: "TFS.WebApi.Exception: 404: Not Found↵    at Object.<anonymous> (https://tfs01/tfs/_apis/public/gallery/publisher/1eslighthouseeng/extension/pr-multi-cherry-pick/1.0.0.46/assetbyname/dist/src/app.js:8:69394)↵    at https://tfs01/tfs/_apis/public/gallery/publisher/1eslighthouseeng/extension/pr-multi-cherry-pick/1.0.0.46/assetbyname/dist/src/app.js:8:67919↵    at Object.next (https://tfs01/tfs/_apis/public/gallery/publisher/1eslighthouseeng/extension/pr-multi-cherry-pick/1.0.0.46/assetbyname/dist/src/app.js:8:68024)↵    at s (https://tfs01/tfs/_apis/public/gallery/publisher/1eslighthouseeng/extension/pr-multi-cherry-pick/1.0.0.46/assetbyname/dist/src/app.js:8:66770)"
status: 404
```

When I manually make a GET request to the URL it works.
We are using a self signed certificate for our server. Maybe this can make a problem for the plugin?

Thanks for the plugin 👍

**Comment by erdennis13** [comment]
Thanks for trying out the extension! We recently realized the extension will only work correctly with Azure DevOps Server 2019 Update 1 and forward. There is an available RC for update 1 [here](https://devblogs.microsoft.com/devops/announcing-azure-devops-server-2019-update-1-rc1/).
 
We are using some newer API calls and will update the documentation accordingly.
